# Generated by Django 4.2.2 on 2025-02-22 16:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('numeroDNI', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('fechaNacimiento', models.CharField(max_length=8)),
                ('anioCenso', models.CharField(max_length=4)),
                ('codigoAutorizacion', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'censo',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('body', models.TextField(blank=True, max_length=5000)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcesoElectoral',
            fields=[
                ('idProcesoElectoral', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nombreProcesoElectoral', models.CharField(max_length=128)),
                ('fechaInicio', models.DateTimeField()),
                ('fechaFin', models.DateTimeField()),
            ],
            options={
                'db_table': 'proceso_electoral',
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCircunscripcion', models.CharField(max_length=16)),
                ('idMesaElectoral', models.CharField(max_length=16)),
                ('idProcesoElectoral', models.CharField(max_length=16)),
                ('nombreCandidatoVotado', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(1)])),
                ('marcaTiempo', models.DateTimeField(auto_now=True)),
                ('codigoRespuesta', models.CharField(default='000', max_length=3)),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votoAppWSServer.censo')),
            ],
            options={
                'db_table': 'voto',
            },
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('censo', 'idProcesoElectoral'), name='unique_blocking_voto'),
        ),
    ]
